Test bookstore using API: register, login, books interaction. Verification with UI test of profile page content after manipulations.
syringomyela/Playwright-practices pull request #3
Opened 2024-12-05 13:42 UTC by syringomyela

2024-12-06 13:47 UTC, Den4ik699 requested changes

2024-12-06 13:47 UTC, Den4ik699 commented on pages/bookstorePages/loginPage.js
> +        await (await this.loginElements()).nameField.fill(username);
Можно здесь использовать только один await?

2024-12-06 13:47 UTC, Den4ik699 commented on pages/bookstorePages/loginPage.js
> +        await (await this.loginElements()).passwordField.fill(password);
Также здесь

2024-12-06 13:47 UTC, Den4ik699 commented on pages/bookstorePages/loginPage.js
> +        await (await this.loginElements()).loginButton.click();
Также здесь

2024-12-06 13:47 UTC, Den4ik699 commented on pages/bookstorePages/loginPage.js
> +        await this.goto(loginURL);
Переход по URL лучше отдельно выносить. Этот метод конкретно для логина

2024-12-06 13:47 UTC, Den4ik699 commented on pages/bookstorePages/profilePage.js
> +    async booksTitlesInProfile(){
по названию непонятно, что делает метод

2024-12-06 13:47 UTC, Den4ik699 commented on pages/bookstorePages/registerPage.js
> +class registerPage extends BasePage {
Все классы названы с большой буквы. Лучше, чтобы было одинаково везде

2024-12-06 13:47 UTC, Den4ik699 commented on pages/bookstorePages/registerPage.js
> +    generateInput(length = 10) {
Снова непонятное название метода. Что такое Input?

2024-12-06 13:47 UTC, Den4ik699 commented on pages/bookstorePages/requests.js
> +export function userCredsBody(){
Непонятно по названию, что делает метод. И для чего он, если ты создал функцию, которая генериркует рандомные логин и пароль

2024-12-06 13:47 UTC, Den4ik699 commented on tests/bookstoreAPITest.spec.js
> +    const addBooksResponse  = await request.post(endpoints.bookstore.books, {
Это лучше вынести в отдельную функцию или класс

2024-12-06 13:47 UTC, Den4ik699 commented on tests/bookstoreAPITest.spec.js
> +    await request.post(endpoints.account.generateToken, {data});
Для чего это вызывается?

2024-12-06 13:47 UTC, Den4ik699 commented on tests/bookstoreAPITest.spec.js
> +    const {actualPage, data, endpoints, } = registerAPI;
что такое actualPage?

2024-12-06 13:47 UTC, Den4ik699 commented on pages/bookstorePages/booksJSON.js
> +
Для чего этот файл?

2024-12-10 07:52 UTC, syringomyela commented on pages/bookstorePages/booksJSON.js
> +
Здесь вся инфа по книгам в джейсоне, чтоб проводить по ней проверку

2024-12-12 15:14 UTC, Den4ik699 commented on pages/bookstorePages/methodsAPI.js
> +    async addBooksToProfile(){
Переделать этот метод. Логин тут точно лишний

2024-12-12 15:14 UTC, Den4ik699 commented on pages/bookstorePages/profilePage.js
> +            tableTitleRow : "span.mr-2 a",
здесь сразу можно делать с this.getElementBySelector

2024-12-12 15:14 UTC, Den4ik699 commented on pages/bookstorePages/profilePage.js
> +        await this.getElementBySelector(this.profilePageElements().dropdownMenu).selectOption("10 rows");
удалить this.getElementBySelector

2024-12-12 15:14 UTC, Den4ik699 commented on pages/bookstorePages/registerPage.js
> +    // generateUserCreds(length = 10) {
удалить закоменитрованый код

2024-12-12 15:14 UTC, Den4ik699 commented on pages/bookstorePages/requests.js
> +export function userAuthentCredsBody(){
либо поменяй название метода, либо используй просто объект

2024-12-12 15:14 UTC, Den4ik699 commented on pages/bookstorePages/requests.js
> +export async function addBooksBody(authToken, userID) {
Удалить эту функцию

2024-12-16 15:19 UTC, Den4ik699 approved these changes

2024-12-16 15:26 UTC, merged